# Generated by Django 3.2.23 on 2024-01-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cw_titre', models.CharField(max_length=128, unique=True, verbose_name='Titre')),
                ('cw_titre_slgify', models.CharField(blank=True, editable=False, max_length=128, verbose_name='Titre Slugify')),
            ],
            options={
                'verbose_name': 'Catégories',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_titre', models.CharField(max_length=128, unique=True, verbose_name='Titre')),
                ('w_titre_slugify', models.CharField(blank=True, editable=False, max_length=128, verbose_name='Titre Slugify')),
                ('w_mots_clefs', models.CharField(blank=True, max_length=512, verbose_name='Mots clefs')),
                ('w_description', models.TextField(blank=True, verbose_name='Description')),
                ('w_description_img', models.URLField(blank=True, max_length=128, verbose_name='Url de la miniature')),
                ('w_contenu', models.TextField(blank=True, verbose_name='Contenu')),
                ('w_right', models.TextField(blank=True, verbose_name='Contenu à droite')),
                ('w_publier', models.BooleanField(default=False, verbose_name='Publié')),
                ('w_reading', models.IntegerField(default=0, verbose_name='Nb Lectures')),
                ('w_publdate', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('w_cat', models.ManyToManyField(blank=True, to='wiki.Cat_Wiki')),
            ],
            options={
                'verbose_name': 'Gestion du Wiki',
                'verbose_name_plural': 'Gestion du Wiki',
                'ordering': ['-w_publdate'],
            },
        ),
    ]
