# Generated by Django 3.2.23 on 2024-01-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiki',
            name='w_description_img',
        ),
        migrations.RemoveField(
            model_name='wiki',
            name='w_mots_clefs',
        ),
        migrations.AlterField(
            model_name='wiki',
            name='w_cat',
            field=models.ManyToManyField(blank=True, to='wiki.Cat_Wiki', verbose_name='Catégories'),
        ),
    ]
