# Generated by Django 3.2.23 on 2024-01-23 16:38

from django.db import migrations, models
# import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20240123_1357'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='wiki',
        #     name='w_contenu',
        #     field=django_quill.fields.QuillField(),
        # ),
        migrations.AlterField(
            model_name='wiki',
            name='w_description',
            field=models.TextField(blank=True, verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='w_publdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Mise à jour le'),
        ),
    ]
