# Generated by Django 3.2.23 on 2024-01-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20240123_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='w_contenu',
            field=models.TextField(blank=True, verbose_name='Contenu'),
        ),
    ]
