# Generated by Django 3.2.23 on 2024-03-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_wiki_w_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='w_publdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Mise à jour le'),
        ),
    ]
