# Generated by Django 3.2.23 on 2024-03-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_wiki_w_publdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wiki',
            options={'ordering': ['w_titre'], 'verbose_name': 'Gestion du Wiki', 'verbose_name_plural': 'Gestion du Wiki'},
        ),
        migrations.AlterField(
            model_name='wiki',
            name='w_publdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Mise à jour le'),
        ),
    ]
