# Generated by Django 3.2.23 on 2024-05-23 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20240423_1338'),
        ('wiki', '0006_auto_20240313_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='w_grp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.groupe', verbose_name='Regroupement'),
        ),
    ]
